//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.gamejam.crashrun.rest;

import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.client.ClientHttpRequestFactory;
import org.springframework.web.client.RestTemplate;

public class RestClient_
    implements RestClient
{

    private RestTemplate restTemplate;
    private String rootUrl;

    public RestClient_() {
        restTemplate = new RestTemplate();
        rootUrl = "http://10.0.0.2";
    }

    public RestClient_(RestTemplate restTemplate) {
        this.restTemplate = restTemplate;
    }

    public RestClient_(ClientHttpRequestFactory requestFactory) {
        restTemplate = new RestTemplate(requestFactory);
    }

    @Override
    public void main() {
        HttpHeaders httpHeaders = new HttpHeaders();
        HttpEntity<Object> requestEntity = new HttpEntity<Object>(httpHeaders);
        restTemplate.exchange(rootUrl.concat("/"), HttpMethod.GET, requestEntity, null).getBody();
    }

}
